
image: python:3.6

options:
  max-time: 10
pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt update
          - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
          - git clone git@bitbucket.org:cse-assemblyline/alv4.git /tmp/assemblyline/
          - cd /tmp/assemblyline
          - mkdir -p /etc/assemblyline/
          - mkdir -p /var/cache/assemblyline/
          - cp test/bitbucket/config.yml /etc/assemblyline
          - pip install .
          - pip install -r test/requirements.txt
          - cd -
          - pip install -r requirements.txt test-requirements.txt
          - pytest -rsx -vv
        services:
          - redis
          - elasticsearch

definitions:
  services:
    elasticsearch:
      image: sgaroncse/elasticsearch:7.0.0
      memory: 768
      environment:
        ES_JAVA_OPTS: '-Xms256m -Xmx256m'
        DISCOVERY_TYPE: 'single-node'

    redis:
      image: redis
      memory: 256
