
options:
  max-time: 10

pipelines:
  default:
    - parallel:
      - step:
          name: Build & Test 3.6
          image: python:3.6
          caches: [pip]
          services: &services
            - redis
            - elasticsearch
          script: &build_test
            - apt update
            - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
            - pip install assemblyline
            - mkdir -p /etc/assemblyline/
            - mkdir -p /var/cache/assemblyline/
            - cp test/bitbucket/config.yml /etc/assemblyline
            - pip install -r test/requirements.txt
            - pip install -e .
            - pytest -rsx -vv
      - step:
          name: Build & Test 3.7
          image: python:3.7
          caches: [pip]
          services: *services
          script: *build_test
      - step:
          name: Build & Test 3.8
          image: python:3.8-rc
          caches: [pip]
          services: *services
          script: *build_test

  tags:
    v*:
      - step:
          name: Build Package
          image: python:3.6
          script:
            - pip install wheel
            - python setup.py bdist_wheel
            - ls dist/
          artifacts:
            - dist/*
      - parallel:
        - step:
            name: Test 3.6
            image: python:3.6
            script: &deploy_test
              - rm -rf al_core setup.py  # Make sure we are running on the package from the prior build
              - apt update
              - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
              - pip install -f dist assemblyline-core
              - mkdir -p /etc/assemblyline/
              - mkdir -p /var/cache/assemblyline/
              - cp test/bitbucket/config.yml /etc/assemblyline
              - pip install -r test/requirements.txt
              - pytest -rsx -vv
        - step:
            name: Test 3.7
            image: python:3.7
            script: *deploy_test
        - step:
            name: Test 3.8
            image: python:3.8-rc
            script: *deploy_test
      - step:
          name: Deploy to Test PyPI
          image: python:3.6
          deployment: test
          script:
            - pip install twine
            - ls dist
            - twine upload --skip-existing --repository-url $TEST_REPOSITORY_URL dist/*
      - step:
          name: Deploy to PyPI
          image: python:3.6
          trigger: manual
          deployment: production
          script:
            - pip install twine
            - ls dist
            - twine upload dist/*

definitions:
  services:
    elasticsearch:
      image: sgaroncse/elasticsearch:7.0.0
      memory: 768
      environment:
        ES_JAVA_OPTS: '-Xms256m -Xmx256m'
        DISCOVERY_TYPE: 'single-node'

    redis:
      image: redis
      memory: 256
