name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: 'ubuntu-18.04'

resources:
  containers:
  - container: redis
    image: redis
    ports:
      - 6379:6379
  - container: elasticsearch
    image: sgaroncse/elasticsearch:7.6.0
    env:
      ES_JAVA_OPTS: "-Xms256m -Xmx512m"
      DISCOVERY_TYPE: 'single-node'
    ports:
      - 9200:9200
  repositories:
  - repository: assemblyline-base
    type: github
    endpoint: github
    name: CybercentreCanada/assemblyline-base

jobs:
- job: run_test
  strategy:
    matrix:
      python3_7:
        python.version: '3.7'
      Python3_8:
        python.version: '3.8'

  timeoutInMinutes: 10
  services:
    elasticsearch: elasticsearch
    redis: redis

  steps:
    - task: UsePythonVersion@0
      displayName: Set python version
      inputs:
        versionSpec: '$(python.version)'
    - checkout: self
    - checkout: assemblyline-base
    - script: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev git
        sudo mkdir -p /etc/assemblyline/
        sudo mkdir -p /var/cache/assemblyline/
        sudo cp pipelines/config.yml /etc/assemblyline
        sudo chmod a+rw /var/cache/assemblyline/
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -U pip cython setuptools
      workingDirectory: $(Pipeline.Workspace)/s/assemblyline-core
      displayName: Setup Environment
    - script: |
        # Try to checkout the matching branch, if the command fails, don't care.
        git checkout -b $(Build.SourceBranchName) -t origin/$(Build.SourceBranchName) || true
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -e .
      displayName: Install assemblyline
      workingDirectory: $(Pipeline.Workspace)/s/assemblyline-base
    - script: |
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -e .[test]
      displayName: Install assemblyline_core
      workingDirectory: $(Pipeline.Workspace)/s/assemblyline-core
    - script: python -m pytest -rsx -vv
      displayName: Test
      workingDirectory: $(Pipeline.Workspace)/s/assemblyline-core
